from setuptools import setup, find_packages

setup(
    name="cha",
    version="0.20.4",
    packages=find_packages(),
    license="MIT",
    description="A simple cli tool that simplifies interactions with AI models, offering features like chat, web scraping, and answer search. It supports multiple platforms and file types, enhancing productivity for all.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    install_requires=[
        "openai==1.93.0",
        "beautifulsoup4==4.13.4",
        "yt-dlp==2025.6.30",
        "youtube-transcript-api==1.1.1",
        "youtube-comment-downloader==0.1.76",
        "PyMuPDF==1.26.3",
        "tiktoken==0.9.0",
        "duckduckgo_search==8.1.0",
        "python-docx==1.2.0",
        "openpyxl==3.1.5",
        "chardet==5.2.0",
        "pathspec==0.12.1",
        "numpy==1.26.4",
        "faster-whisper==1.1.1",
        "moviepy==2.2.1",
        "pillow==11.3.0",
        "pytesseract==0.3.13",
        "mutagen==1.47.0",
    ],
    python_requires=">=3.9.2",
    entry_points={
        "console_scripts": ["cha = cha.main:cli"],
    },
)
