from setuptools import setup, find_packages

setup(
    name="cha",
    version="0.22.12",
    packages=find_packages(),
    license="MIT",
    description="A lightweight CLI tool for terminal-based AI interactions across multiple platforms (Ollama, OpenAI, Anthropic, Google, etc) with full user control",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    install_requires=[
        "openai==1.97.1",
        "beautifulsoup4==4.13.4",
        "yt-dlp==2025.7.21",
        "youtube-transcript-api==1.2.1",
        "youtube-comment-downloader==0.1.76",
        "PyMuPDF==1.26.3",
        "tiktoken==0.9.0",
        "ddgs==9.4.3",
        "python-docx==1.2.0",
        "openpyxl==3.1.5",
        "chardet==5.2.0",
        "pathspec==0.12.1",
        "numpy==1.26.4",
        "faster-whisper==1.1.1",
        "moviepy==2.2.1",
        "pillow==11.3.0",
        "pytesseract==0.3.13",
        "mutagen==1.47.0",
        "PyYAML==6.0.2",
        "sounddevice==0.5.2",
        "scipy==1.16.0",
        "lingua-language-detector==2.1.1",
    ],
    python_requires=">=3.11",
    entry_points={
        "console_scripts": ["cha = cha.main:cli"],
    },
)
